# Generated by Django 5.1 on 2025-04-18 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0008_alter_customuser_email'),
    ]

    operations = [
    ]
