# Generated by Django 5.1.7 on 2025-04-17 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0005_treatment'),
        ('reports', '0002_report_assigned_doctor_report_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='treatment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='treatment_reports', to='chatbot.treatment'),
        ),
    ]
