# Generated by Django 5.1.7 on 2025-04-17 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_report_treatment'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='pdf_blob',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
