# Generated by Django 5.1.7 on 2025-04-17 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0005_treatment'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatment',
            name='reqd',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
