name: Django + Pytest CI

on:
  push:
    branches: ['**']
  pull_request:
    branches: ['**']

jobs:
  test:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
        working-directory: Merilife/MediBot/chatbot-website

      - name: Run migrations
        run: python manage.py migrate --noinput
        working-directory: Merilife/MediBot/chatbot-website

      - name: Run tests
        run: pytest --maxfail=1 --disable-warnings -q
        working-directory: Merilife/MediBot/chatbot-website
